spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbiinfo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
#  mvc:
#    view:
#      prefix: /pages/
#      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
 # type-aliases-package: springboot.demo.POJO.*
logging:
    level:
      springboot.demo:
            mappers: debug